# https://taskfile.dev/installation

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I . ./lp.proto --go_out=../../gen/go/lp --go_opt=paths=source_relative --go-grpc_out=../../gen/go/lp --go-grpc_opt=paths=source_relative
